"""empty message

Revision ID: a59d4451b08b
Revises: 
Create Date: 2019-08-29 08:56:43.403318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a59d4451b08b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmpUsers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tmpUsers")
    # ### end Alembic commands ###
